### PR TITLE
Fix #639: fix malformed vcf file generation

### LINKED ISSUE #639: Freebayes genereted gvcf files contains errors
Hi,

First I want to thank you for freebayes, it's a great tool!

I am generating gvcf files for over a 100 samples using a reference genome of about 10^9 bp.  I call variants using the folowing command line:
**freebayes --genotype-qualities --strict-vcf --ploidy 2 -f {refGenome} --gvcf --gvcf-dont-use-chunk true --vcf {variantFile} {dedupBamFile}**

Variant calling does not fail, but downstream splitting into SNP and INDEL using **gatk SelectVariant** does fail on several samples with the same error (except for the line number):
**The provided VCF file is malformed at approximately line number 973642001: empty alleles are not permitted in VCF records**

When investigating the gvcf generated by freebayes (relevant parts only shown below, escaped some stars to avoid markdown issues) I noticed that those empty alleles are part of a chunk in the next contig with coordinates of the previous contig. In the example given, I get a chunk in contig SWJQ01000002.1 for the range 8013061 - 8013090. This should be in contig SWJQ01000001.1 and it should not be as a chunk (see command line above). The same type of error happens for the next scaffolds (only 2 more shown in excerpt, many more in the gvcf).  About 20% of my samples produce a gvcf with this type of errors, all were analyzed using the same reference genome and freebayes command line. Unless I missed something, this looks like a bug?

##fileformat=VCFv4.2
##fileDate=20200820
##source=freeBayes v1.3.2-46-g2c1e395
##reference=XXX
##contig=<ID=SWJQ01000001.1,length=**8013090**>
##contig=<ID=**SWJQ01000002.1**,length=5190156>
##contig=<ID=SWJQ01000003.1,length=2769777>
##contig=<ID=SWJQ01000004.1,length=397823>
...
SWJQ01000001.1  8013059 .       T       <\*>     0       .       DP=0;END=8013059;MIN_DP=0       GQ:DP:MIN_DP:QR:RO:QA:AO        -0:0:0:-0:0:-0:0
SWJQ01000001.1  8013060 .       G       <\*>     0       .       DP=0;END=8013060;MIN_DP=0       GQ:DP:MIN_DP:QR:RO:QA:AO        -0:0:0:-0:0:-0:0
**SWJQ01000002.1**  **8013061** .       .       <\*>     0       .       DP=0;END=8013090;MIN_DP=0       GQ:DP:MIN_DP:QR:RO:QA:AO        -0:0:0:-0:0:-0:0
SWJQ01000002.1  1       .       T       <\*>     0       .       DP=0;END=1;MIN_DP=0     GQ:DP:MIN_DP:QR:RO:QA:AO        -0:0:0:-0:0:-0:0
SWJQ01000002.1  2       .       A       <\*>     0       .       DP=10;END=2;MIN_DP=10   GQ:DP:MIN_DP:QR:RO:QA:AO        370:10:10:370:10:-0:0
...
SWJQ01000003.1  5190107 .       .       <\*>     0       .       DP=0;END=5190156;MIN_DP=0       GQ:DP:MIN_DP:QR:RO:QA:AO        -0:0:0:-0:0:-0:0
...
SWJQ01000004.1  2769587 .       .       <\*>     0       .       DP=0;END=2769777;MIN_DP=0       GQ:DP:MIN_DP:QR:RO:QA:AO        -0:0:0:-0:0:-0:0
...

Yannick

### PR DESCRIPTION
**Pull request by chris7716**
Fixes #639

Output for the test data provided in: https://github.com/freebayes/freebayes/issues/639#issuecomment-3844177911

```
grep -v '^##' test.vcf
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	unknown
chr1	18	.	A	<*>	0	.	DP=1;END=18;MIN_DP=1	GQ:DP:MIN_DP:QR:RO:QA:AO	40:1:1:40:1:0:0
chr1	19	.	A	<*>	0	.	DP=2;END=19;MIN_DP=2	GQ:DP:MIN_DP:QR:RO:QA:AO	80:2:2:80:2:0:0
chr1	20	.	A	<*>	0	.	DP=2;END=20;MIN_DP=2	GQ:DP:MIN_DP:QR:RO:QA:AO	80:2:2:80:2:0:0
chr2	5	.	C	<*>	0	.	DP=1;END=5;MIN_DP=1	GQ:DP:MIN_DP:QR:RO:QA:AO	40:1:1:40:1:0:0
chr2	6	.	C	<*>	0	.	DP=1;END=6;MIN_DP=1	GQ:DP:MIN_DP:QR:RO:QA:AO	40:1:1:40:1:0:0
chr2	7	.	C	<*>	0	.	DP=1;END=7;MIN_DP=1	GQ:DP:MIN_DP:QR:RO:QA:AO	40:1:1:40:1:0:0
chr2	8	.	C	<*>	0	.	DP=1;END=8;MIN_DP=1	GQ:DP:MIN_DP:QR:RO:QA:AO	40:1:1:40:1:0:0
chr2	9	.	C	<*>	0	.	DP=1;END=9;MIN_DP=1	GQ:DP:MIN_DP:QR:RO:QA:AO	40:1:1:40:1:0:0
chr2	10	.	C	<*>	0	.	DP=1;END=10;MIN_DP=1	GQ:DP:MIN_DP:QR:RO:QA:AO	40:1:1:40:1:0:0
chr2	11	.	C	<*>	0	.	DP=1;END=11;MIN_DP=1	GQ:DP:MIN_DP:QR:RO:QA:AO	40:1:1:40:1:0:0
chr2	12	.	C	<*>	0	.	DP=1;END=12;MIN_DP=1	GQ:DP:MIN_DP:QR:RO:QA:AO	40:1:1:40:1:0:0
chr2	13	.	C	<*>	0	.	DP=1;END=13;MIN_DP=1	GQ:DP:MIN_DP:QR:RO:QA:AO	40:1:1:40:1:0:0
chr2	14	.	C	<*>	0	.	DP=1;END=14;MIN_DP=1	GQ:DP:MIN_DP:QR:RO:QA:AO	40:1:1:40:1:0:0
chr2	15	.	C	<*>	0	.	DP=0;END=15;MIN_DP=0	GQ:DP:MIN_DP:QR:RO:QA:AO	-0:0:0:0:0:0:0
chr2	16	.	C	<*>	0	.	DP=0;END=16;MIN_DP=0	GQ:DP:MIN_DP:QR:RO:QA:AO	-0:0:0:0:0:0:0
```

### CODE REVIEW

File: src/ResultData.cpp [hunk 1]
```diff
@@ -662,9 +662,9 @@ vcflib::Variant& Results::gvcf(
      };
 
     // set up site call
-    var.ref = parser->referenceSubstr(startPos, 1);
+    var.ref = uppercase(parser->reference.getSubSequence(startChrom, startPos, 1));
     var.alt.push_back("<*>");
-    var.sequenceName = parser->currentSequenceName;
+    var.sequenceName = startChrom;
```
Comment (chris7716) [inline src/ResultData.cpp:667]: According to the following logic, the buffer is flushed at the start of each loop iteration, before processing the new position. The parser is already advanced to the next position while we trying to flush the buffer.

https://github.com/freebayes/freebayes/blob/7e1ef1a77f722732a82cf787dc37cacd700749b3/src/freebayes.cpp#L126-L138

The issue occured because, even though we correctly detected the boundary change (`startChrom != parser->currentSequenceName`) in line 653, we still used current sequence which is already advanced in the parser.

For an example, when we try to flush chr1:20, parser->currentSequenceName is already chr2.

Because of that, instead of using `var.sequenceName = parser->currentSequenceName`, we should use `var.sequenceName = startChrom` which corresponds to the buffer which we are going to flush.

Also `parser->referenceSubstr` internally uses `parser->currentSequenceName` when computing the referenceSubstr which is not the correct referrence that we are flushing.

https://github.com/freebayes/freebayes/blob/7e1ef1a77f722732a82cf787dc37cacd700749b3/src/AlleleParser.cpp#L966-L968

Because of that, the best way is to call `getSubSequence()` with the `startChrom`.

**Comment by chris7716** [comment]
Removed the regression test from the CI due to the flaky behavior.

I built the master and this branch using Guix and compared the output using the `regression_test.sh`.

```
hasitha@balg01:~/data/projects/freebayes$ bash test/regression_test.sh
Using freebayes: /home/hasitha/data/projects/freebayes/test/../build/freebayes
========================================
FreeBayes Regression Test Suite
========================================

Running test: basic
  binary:    /home/hasitha/data/projects/freebayes/test/../build/freebayes
  reference: /home/hasitha/data/projects/freebayes/test/data/test.ref
  bam:       /home/hasitha/data/projects/freebayes/test/data/test.bam
  args:      <none>
  command:   /home/hasitha/data/projects/freebayes/test/../build/freebayes -f /home/hasitha/data/projects/freebayes/test/data/test.ref  /home/hasitha/data/projects/freebayes/test/data/test.bam
Baseline file: /home/hasitha/data/projects/freebayes-baseline//basic.vcf
PASSED

Running test: region
  binary:    /home/hasitha/data/projects/freebayes/test/../build/freebayes
  reference: /home/hasitha/data/projects/freebayes/test/data/test.ref
  bam:       /home/hasitha/data/projects/freebayes/test/data/test.bam
  args:      -r ref:1-11
  command:   /home/hasitha/data/projects/freebayes/test/../build/freebayes -f /home/hasitha/data/projects/freebayes/test/data/test.ref -r ref:1-11 /home/hasitha/data/projects/freebayes/test/data/test.bam
Baseline file: /home/hasitha/data/projects/freebayes-baseline//region.vcf
PASSED

Running test: min_alt_frac
  binary:    /home/hasitha/data/projects/freebayes/test/../build/freebayes
  reference: /home/hasitha/data/projects/freebayes/test/data/test.ref
  bam:       /home/hasitha/data/projects/freebayes/test/data/test.bam
  args:      -F 0.1 -C 1
  command:   /home/hasitha/data/projects/freebayes/test/../build/freebayes -f /home/hasitha/data/projects/freebayes/test/data/test.ref -F 0.1 -C 1 /home/hasitha/data/projects/freebayes/test/data/test.bam
Baseline file: /home/hasitha/data/projects/freebayes-baseline//min_alt_frac.vcf
PASSED

Running test: tiny_chr22
  binary:    /home/hasitha/data/projects/freebayes/test/../build/freebayes
  reference: /home/hasitha/data/projects/freebayes/test/tiny/q.fa
  bam:       /home/hasitha/data/projects/freebayes/test/tiny/NA12878.chr22.tiny.bam
  args:      -r q:1-1000
  command:   /home/hasitha/data/projects/freebayes/test/../build/freebayes -f /home/hasitha/data/projects/freebayes/test/tiny/q.fa -r q:1-1000 /home/hasitha/data/projects/freebayes/test/tiny/NA12878.chr22.tiny.bam
Baseline file: /home/hasitha/data/projects/freebayes-baseline//tiny_chr22.vcf
PASSED

Running test: tiny_chr22_region2
  binary:    /home/hasitha/data/projects/freebayes/test/../build/freebayes
  reference: /home/hasitha/data/projects/freebayes/test/tiny/q.fa
  bam:       /home/hasitha/data/projects/freebayes/test/tiny/NA12878.chr22.tiny.bam
  args:      -r q:1000-5000
  command:   /home/hasitha/data/projects/freebayes/test/../build/freebayes -f /home/hasitha/data/projects/freebayes/test/tiny/q.fa -r q:1000-5000 /home/hasitha/data/projects/freebayes/test/tiny/NA12878.chr22.tiny.bam
Baseline file: /home/hasitha/data/projects/freebayes-baseline//tiny_chr22_region2.vcf
PASSED

Running test: tiny_chr22_region3
  binary:    /home/hasitha/data/projects/freebayes/test/../build/freebayes
  reference: /home/hasitha/data/projects/freebayes/test/tiny/q.fa
  bam:       /home/hasitha/data/projects/freebayes/test/tiny/NA12878.chr22.tiny.bam
  args:      -r q:5000-10000
  command:   /home/hasitha/data/projects/freebayes/test/../build/freebayes -f /home/hasitha/data/projects/freebayes/test/tiny/q.fa -r q:5000-10000 /home/hasitha/data/projects/freebayes/test/tiny/NA12878.chr22.tiny.bam
Baseline file: /home/hasitha/data/projects/freebayes-baseline//tiny_chr22_region3.vcf
PASSED

Running test: tiny_chr22_full
  binary:    /home/hasitha/data/projects/freebayes/test/../build/freebayes
  reference: /home/hasitha/data/projects/freebayes/test/tiny/q.fa
  bam:       /home/hasitha/data/projects/freebayes/test/tiny/NA12878.chr22.tiny.bam
  args:      <none>
  command:   /home/hasitha/data/projects/freebayes/test/../build/freebayes -f /home/hasitha/data/projects/freebayes/test/tiny/q.fa  /home/hasitha/data/projects/freebayes/test/tiny/NA12878.chr22.tiny.bam
Baseline file: /home/hasitha/data/projects/freebayes-baseline//tiny_chr22_full.vcf
PASSED

Running test: tiny_chr22_gvcf
  binary:    /home/hasitha/data/projects/freebayes/test/../build/freebayes
  reference: /home/hasitha/data/projects/freebayes/test/tiny/q.fa
  bam:       /home/hasitha/data/projects/freebayes/test/tiny/NA12878.chr22.tiny.bam
  args:      -r q:1-1000 --gvcf
  command:   /home/hasitha/data/projects/freebayes/test/../build/freebayes -f /home/hasitha/data/projects/freebayes/test/tiny/q.fa -r q:1-1000 --gvcf /home/hasitha/data/projects/freebayes/test/tiny/NA12878.chr22.tiny.bam
Baseline file: /home/hasitha/data/projects/freebayes-baseline//tiny_chr22_gvcf.vcf
PASSED

Running test: tiny_chr22_gvcf_nochunk
  binary:    /home/hasitha/data/projects/freebayes/test/../build/freebayes
  reference: /home/hasitha/data/projects/freebayes/test/tiny/q.fa
  bam:       /home/hasitha/data/projects/freebayes/test/tiny/NA12878.chr22.tiny.bam
  args:      -r q:1-1000 --gvcf --gvcf-dont-use-chunk true
  command:   /home/hasitha/data/projects/freebayes/test/../build/freebayes -f /home/hasitha/data/projects/freebayes/test/tiny/q.fa -r q:1-1000 --gvcf --gvcf-dont-use-chunk true /home/hasitha/data/projects/freebayes/test/tiny/NA12878.chr22.tiny.bam
Baseline file: /home/hasitha/data/projects/freebayes-baseline//tiny_chr22_gvcf_nochunk.vcf
PASSED

Running test: tiny_chr22_min_mapq
  binary:    /home/hasitha/data/projects/freebayes/test/../build/freebayes
  reference: /home/hasitha/data/projects/freebayes/test/tiny/q.fa
  bam:       /home/hasitha/data/projects/freebayes/test/tiny/NA12878.chr22.tiny.bam
  args:      -r q:1-1000 --min-mapping-quality 20
  command:   /home/hasitha/data/projects/freebayes/test/../build/freebayes -f /home/hasitha/data/projects/freebayes/test/tiny/q.fa -r q:1-1000 --min-mapping-quality 20 /home/hasitha/data/projects/freebayes/test/tiny/NA12878.chr22.tiny.bam
Baseline file: /home/hasitha/data/projects/freebayes-baseline//tiny_chr22_min_mapq.vcf
PASSED

Running test: tiny_chr22_min_baseq
  binary:    /home/hasitha/data/projects/freebayes/test/../build/freebayes
  reference: /home/hasitha/data/projects/freebayes/test/tiny/q.fa
  bam:       /home/hasitha/data/projects/freebayes/test/tiny/NA12878.chr22.tiny.bam
  args:      -r q:1-1000 --min-base-quality 20
  command:   /home/hasitha/data/projects/freebayes/test/../build/freebayes -f /home/hasitha/data/projects/freebayes/test/tiny/q.fa -r q:1-1000 --min-base-quality 20 /home/hasitha/data/projects/freebayes/test/tiny/NA12878.chr22.tiny.bam
Baseline file: /home/hasitha/data/projects/freebayes-baseline//tiny_chr22_min_baseq.vcf
PASSED

Running test: tiny_chr22_limit_cov
  binary:    /home/hasitha/data/projects/freebayes/test/../build/freebayes
  reference: /home/hasitha/data/projects/freebayes/test/tiny/q.fa
  bam:       /home/hasitha/data/projects/freebayes/test/tiny/NA12878.chr22.tiny.bam
  args:      -r q:1-1000 --limit-coverage 20
  command:   /home/hasitha/data/projects/freebayes/test/../build/freebayes -f /home/hasitha/data/projects/freebayes/test/tiny/q.fa -r q:1-1000 --limit-coverage 20 /home/hasitha/data/projects/freebayes/test/tiny/NA12878.chr22.tiny.bam
Baseline file: /home/hasitha/data/projects/freebayes-baseline//tiny_chr22_limit_cov.vcf
PASSED

Running test: tiny_chr22_ploidy1
  binary:    /home/hasitha/data/projects/freebayes/test/../build/freebayes
  reference: /home/hasitha/data/projects/freebayes/test/tiny/q.fa
  bam:       /home/hasitha/data/projects/freebayes/test/tiny/NA12878.chr22.tiny.bam
  args:      -r q:1-1000 --ploidy 1
  command:   /home/hasitha/data/projects/freebayes/test/../build/freebayes -f /home/hasitha/data/projects/freebayes/test/tiny/q.fa -r q:1-1000 --ploidy 1 /home/hasitha/data/projects/freebayes/test/tiny/NA12878.chr22.tiny.bam
Baseline file: /home/hasitha/data/projects/freebayes-baseline//tiny_chr22_ploidy1.vcf
PASSED

Running test: tiny_chr22_hap_len_0
  binary:    /home/hasitha/data/projects/freebayes/test/../build/freebayes
  reference: /home/hasitha/data/projects/freebayes/test/tiny/q.fa
  bam:       /home/hasitha/data/projects/freebayes/test/tiny/NA12878.chr22.tiny.bam
  args:      -r q:1-1000 --haplotype-length 0
  command:   /home/hasitha/data/projects/freebayes/test/../build/freebayes -f /home/hasitha/data/projects/freebayes/test/tiny/q.fa -r q:1-1000 --haplotype-length 0 /home/hasitha/data/projects/freebayes/test/tiny/NA12878.chr22.tiny.bam
Baseline file: /home/hasitha/data/projects/freebayes-baseline//tiny_chr22_hap_len_0.vcf
PASSED

========================================
Summary:
  Passed: 14
  Failed: 0
All tests passed!
```

FIles inside `/home/hasitha/data/projects/freebayes-baseline` were generated using the master branch.

Output of the each command in every test was compared against the corresponding file inside `freebayes-baseline`
